/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppSignupRouteImport } from './routes/_app/signup'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppAuthenticatedRouteImport } from './routes/_app/_authenticated'
import { Route as AppAuthenticatedIndexRouteImport } from './routes/_app/_authenticated/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppAuthenticatedRoomsRoomIdRouteImport } from './routes/_app/_authenticated/rooms/$roomId'
import { Route as AppAuthenticatedMerchantsMerchantIdRouteImport } from './routes/_app/_authenticated/merchants/$merchantId'
import { Route as AppAuthenticatedItemsItemIdRouteImport } from './routes/_app/_authenticated/items/$itemId'
import { Route as AppAuthenticatedCategoriesCategoryIdRouteImport } from './routes/_app/_authenticated/categories/$categoryId'

const AppSignupRoute = AppSignupRouteImport.update({
  id: '/_app/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/_app/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedRoute = AppAuthenticatedRouteImport.update({
  id: '/_app/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedIndexRoute = AppAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthenticatedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedRoomsRoomIdRoute =
  AppAuthenticatedRoomsRoomIdRouteImport.update({
    id: '/rooms/$roomId',
    path: '/rooms/$roomId',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedMerchantsMerchantIdRoute =
  AppAuthenticatedMerchantsMerchantIdRouteImport.update({
    id: '/merchants/$merchantId',
    path: '/merchants/$merchantId',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedItemsItemIdRoute =
  AppAuthenticatedItemsItemIdRouteImport.update({
    id: '/items/$itemId',
    path: '/items/$itemId',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedCategoriesCategoryIdRoute =
  AppAuthenticatedCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppAuthenticatedIndexRoute
  '/login': typeof AppLoginRoute
  '/signup': typeof AppSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/categories/$categoryId': typeof AppAuthenticatedCategoriesCategoryIdRoute
  '/items/$itemId': typeof AppAuthenticatedItemsItemIdRoute
  '/merchants/$merchantId': typeof AppAuthenticatedMerchantsMerchantIdRoute
  '/rooms/$roomId': typeof AppAuthenticatedRoomsRoomIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof AppLoginRoute
  '/signup': typeof AppSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof AppAuthenticatedIndexRoute
  '/categories/$categoryId': typeof AppAuthenticatedCategoriesCategoryIdRoute
  '/items/$itemId': typeof AppAuthenticatedItemsItemIdRoute
  '/merchants/$merchantId': typeof AppAuthenticatedMerchantsMerchantIdRoute
  '/rooms/$roomId': typeof AppAuthenticatedRoomsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app/_authenticated': typeof AppAuthenticatedRouteWithChildren
  '/_app/login': typeof AppLoginRoute
  '/_app/signup': typeof AppSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/_authenticated/': typeof AppAuthenticatedIndexRoute
  '/_app/_authenticated/categories/$categoryId': typeof AppAuthenticatedCategoriesCategoryIdRoute
  '/_app/_authenticated/items/$itemId': typeof AppAuthenticatedItemsItemIdRoute
  '/_app/_authenticated/merchants/$merchantId': typeof AppAuthenticatedMerchantsMerchantIdRoute
  '/_app/_authenticated/rooms/$roomId': typeof AppAuthenticatedRoomsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/api/auth/$'
    | '/categories/$categoryId'
    | '/items/$itemId'
    | '/merchants/$merchantId'
    | '/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/api/auth/$'
    | '/'
    | '/categories/$categoryId'
    | '/items/$itemId'
    | '/merchants/$merchantId'
    | '/rooms/$roomId'
  id:
    | '__root__'
    | '/_app/_authenticated'
    | '/_app/login'
    | '/_app/signup'
    | '/api/auth/$'
    | '/_app/_authenticated/'
    | '/_app/_authenticated/categories/$categoryId'
    | '/_app/_authenticated/items/$itemId'
    | '/_app/_authenticated/merchants/$merchantId'
    | '/_app/_authenticated/rooms/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppAuthenticatedRoute: typeof AppAuthenticatedRouteWithChildren
  AppLoginRoute: typeof AppLoginRoute
  AppSignupRoute: typeof AppSignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app/signup': {
      id: '/_app/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AppSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_authenticated': {
      id: '/_app/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_authenticated/': {
      id: '/_app/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppAuthenticatedIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_authenticated/rooms/$roomId': {
      id: '/_app/_authenticated/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof AppAuthenticatedRoomsRoomIdRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/_app/_authenticated/merchants/$merchantId': {
      id: '/_app/_authenticated/merchants/$merchantId'
      path: '/merchants/$merchantId'
      fullPath: '/merchants/$merchantId'
      preLoaderRoute: typeof AppAuthenticatedMerchantsMerchantIdRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/_app/_authenticated/items/$itemId': {
      id: '/_app/_authenticated/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof AppAuthenticatedItemsItemIdRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/_app/_authenticated/categories/$categoryId': {
      id: '/_app/_authenticated/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof AppAuthenticatedCategoriesCategoryIdRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
  }
}

interface AppAuthenticatedRouteChildren {
  AppAuthenticatedIndexRoute: typeof AppAuthenticatedIndexRoute
  AppAuthenticatedCategoriesCategoryIdRoute: typeof AppAuthenticatedCategoriesCategoryIdRoute
  AppAuthenticatedItemsItemIdRoute: typeof AppAuthenticatedItemsItemIdRoute
  AppAuthenticatedMerchantsMerchantIdRoute: typeof AppAuthenticatedMerchantsMerchantIdRoute
  AppAuthenticatedRoomsRoomIdRoute: typeof AppAuthenticatedRoomsRoomIdRoute
}

const AppAuthenticatedRouteChildren: AppAuthenticatedRouteChildren = {
  AppAuthenticatedIndexRoute: AppAuthenticatedIndexRoute,
  AppAuthenticatedCategoriesCategoryIdRoute:
    AppAuthenticatedCategoriesCategoryIdRoute,
  AppAuthenticatedItemsItemIdRoute: AppAuthenticatedItemsItemIdRoute,
  AppAuthenticatedMerchantsMerchantIdRoute:
    AppAuthenticatedMerchantsMerchantIdRoute,
  AppAuthenticatedRoomsRoomIdRoute: AppAuthenticatedRoomsRoomIdRoute,
}

const AppAuthenticatedRouteWithChildren =
  AppAuthenticatedRoute._addFileChildren(AppAuthenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppAuthenticatedRoute: AppAuthenticatedRouteWithChildren,
  AppLoginRoute: AppLoginRoute,
  AppSignupRoute: AppSignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
