/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppAuthenticatedRouteImport } from './routes/_app/_authenticated'
import { Route as AppAuthenticatedIndexRouteImport } from './routes/_app/_authenticated/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppLoginRoute = AppLoginRouteImport.update({
  id: '/_app/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedRoute = AppAuthenticatedRouteImport.update({
  id: '/_app/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedIndexRoute = AppAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthenticatedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppAuthenticatedIndexRoute
  '/login': typeof AppLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof AppLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof AppAuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app/_authenticated': typeof AppAuthenticatedRouteWithChildren
  '/_app/login': typeof AppLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/_authenticated/': typeof AppAuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/api/auth/$' | '/'
  id:
    | '__root__'
    | '/_app/_authenticated'
    | '/_app/login'
    | '/api/auth/$'
    | '/_app/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppAuthenticatedRoute: typeof AppAuthenticatedRouteWithChildren
  AppLoginRoute: typeof AppLoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_authenticated': {
      id: '/_app/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_authenticated/': {
      id: '/_app/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppAuthenticatedIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAuthenticatedRouteChildren {
  AppAuthenticatedIndexRoute: typeof AppAuthenticatedIndexRoute
}

const AppAuthenticatedRouteChildren: AppAuthenticatedRouteChildren = {
  AppAuthenticatedIndexRoute: AppAuthenticatedIndexRoute,
}

const AppAuthenticatedRouteWithChildren =
  AppAuthenticatedRoute._addFileChildren(AppAuthenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppAuthenticatedRoute: AppAuthenticatedRouteWithChildren,
  AppLoginRoute: AppLoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
